package com.bytest.autotest.dao;

import com.bytest.autotest.domain.EasyuiNav;
import java.util.List;

public interface EasyuiNavDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easyui_nav
     *
     * @mbggenerated Sat May 02 15:19:01 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easyui_nav
     *
     * @mbggenerated Sat May 02 15:19:01 CST 2020
     */
    int insert(EasyuiNav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easyui_nav
     *
     * @mbggenerated Sat May 02 15:19:01 CST 2020
     */
    EasyuiNav selectByPrimaryKey(Integer id);

    List<EasyuiNav> selectByNid(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easyui_nav
     *
     * @mbggenerated Sat May 02 15:19:01 CST 2020
     */
    List<EasyuiNav> selectAll();
    List<EasyuiNav> selectOpen(String state);

    List<EasyuiNav> getMenuChildren(String state);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easyui_nav
     *
     * @mbggenerated Sat May 02 15:19:01 CST 2020
     */
    int updateByPrimaryKey(EasyuiNav record);
}